### ISSUE TITLE
System.NullReferenceException in MexTK.Commands.CmdFighterFunction.CompileInput

### ISSUE THREAD

**Issue by CaioIcy** [UnclePunch/Training-Mode#15]
In my Windows 10 machine, running the `build.bat` for any of the `patch/events/...` yields the following:

```
H:\...\Training-Mode\patch\events\ledgedash>xcopy /s /y "assets\ldshData.dat" "output/EvLdsh.dat"
assets\ldshData.dat
1 File(s) copied                                                                                                                                                                                

H:\...\Training-Mode\patch\events\ledgedash>"../../../MexTK/MexTK.exe" -ff -i "source/ledgedash.c" -s evFunction -dat "output/EvLdsh.dat" -t "../../../MexTK/evFunction.txt" -q -ow -w -c -l "../../../MexTK/melee.link" -op 1

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at MexTK.Commands.CmdFighterFunction.CompileInput(String[] inputs, String[] funcTable, LinkFile link, Boolean quiet, Boolean disableWarnings, Boolean clean, Int32 optimizationLevel)
    at MexTK.Commands.CmdFighterFunction.DoIt(String[] args)
    at MexTK.Program.Main(String[] args)                                                                                                                                                            

H:\...\Training-Mode\patch\events\ledgedash>"../../../MexTK/MexTK.exe" -trim "output/EvLdsh.dat"
H:\...\Training-Mode\patch\events\ledgedash>pause

Press any key to continue . . .
```

It outputs a new `EvLdsh.dat`, but when I imported it over the official v3.0 Alpha 3 through GCRebuilder the event crashes on load.

**Comment by DewanckelJonas** [comment]
I am having the same issue currently. Did you find a solution or did you give up on it?

**Comment by DewanckelJonas** [comment]
I got the solution from UnclePunch. You need to install Devkitppc to be able to compile the c code.

**Comment by CaioIcy** [comment]
Installing devkitPro was the solution, thank you @DewanckelJonas !
For others that see this, you can get it here: https://devkitpro.org/wiki/Getting_Started
